runtime: python311

entrypoint: gunicorn --worker-class eventlet -w 1 run:app

instance_class: F2

env_variables:
  # Add any environment variables here
  FLASK_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# optional settings
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
