[tool.poetry]
name = "webtechnologienhausarbeit"
version = "0.1.0"
description = ""
authors = ["Nils Baxheinrich <nils.baxheinrich@gmx.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.29"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
