"""empty message

Revision ID: 18a6ff0c1ad4
Revises: ff05de1e9831
Create Date: 2024-05-27 08:39:57.826102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a6ff0c1ad4'
down_revision = 'ff05de1e9831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draw_stack', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('draw_stack')

    # ### end Alembic commands ###
