"""empty message

Revision ID: 4feb98aa72d3
Revises: a1846d088728
Create Date: 2024-05-16 12:28:16.067425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4feb98aa72d3'
down_revision = 'a1846d088728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_cards', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
