"""empty message

Revision ID: 647e4123dddd
Revises: 87d668709157
Create Date: 2024-05-10 11:49:30.429967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647e4123dddd'
down_revision = '87d668709157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
