"""empty message

Revision ID: 73955f05e059
Revises: 647e4123dddd
Create Date: 2024-05-10 14:25:37.892551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73955f05e059'
down_revision = '647e4123dddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Integer(), nullable=False))
        batch_op.drop_column('protection')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protection', sa.INTEGER(), nullable=False))
        batch_op.drop_column('public')

    # ### end Alembic commands ###
