"""empty message

Revision ID: 802999480812
Revises: 18a6ff0c1ad4
Create Date: 2024-05-28 08:33:34.403632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802999480812'
down_revision = '18a6ff0c1ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_drawn', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('has_drawn')

    # ### end Alembic commands ###
