"""empty message

Revision ID: 87d668709157
Revises: c36f436b01a1
Create Date: 2024-05-08 11:42:54.011909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d668709157'
down_revision = 'c36f436b01a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protection', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('protection')

    # ### end Alembic commands ###
